# monkey3d/config_example.yaml

fps: 30.0

rois:
  - name: left_wall
    surface: left
    vertices:
      - [x1, y1]
      - [x2, y2]
      - [x3, y3]
      - [x4, y4]

  - name: right_wall
    surface: right
    vertices:
      - [x1, y1]
      - [x2, y2]
      - [x3, y3]
      - [x4, y4]

  - name: back_wall
    surface: back
    vertices:
      - [x1, y1]
      - [x2, y2]
      - [x3, y3]
      - [x4, y4]

  - name: bottom
    surface: bottom
    vertices:
      - [x1, y1]
      - [x2, y2]
      - [x3, y3]
      - [x4, y4]

